server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: 1234

thymeleaf:
  prefix: classpath:/static/
  suffix: .html